# Message that contains Action Unit, i.e. a decomposition of human facial movements that produce an expression

# Identifier of the Action Unit, where OpenFace recognises AU01, AU02, AU04, AU05, AU06, AU07, AU09,  AU10,  AU12,  AU14,  AU15,  AU17,  AU20,  AU23,  AU25,  AU26,  AU28, and AU45
string name
# Presence determines if Action Unit is visible on the face
bool presence
# Intensity of the Action Unit on a 5 point scale
float64 intensity
